# Create a list of known MagicUI components
components=(
"marquee"
"terminal"
"hero-video-dialog"
"bento-grid"
"animated-list"
"dock"
"globe"
"tweet-card"
"orbiting-circles"
"avatar-circles"
"icon-cloud"
"animated-circular-progress-bar"
"file-tree"
"code-comparison"
"script-copy-btn"
"scroll-progress"
"lens"
"pointer"
"smooth-cursor"
"animated-beam"
"border-beam"
"shine-border"
"magic-card"
"meteors"
"neon-gradient-card"
"confetti"
"particles"
"cool-mode"
"scratch-to-reveal"
"text-animate"
"line-shadow-text"
"aurora-text"
"video-text"
"number-ticker"
"animated-shiny-text"
"animated-gradient-text"
"text-reveal"
"hyper-text"
"word-rotate"
"typing-animation"
"scroll-based-velocity"
"flip-text"
"box-reveal"
"sparkles-text"
"morphing-text"
"spinning-text"
"rainbow-button"
"shimmer-button"
"shiny-button"
"interactive-hover-button"
"animated-subscribe-button"
"pulsating-button"
"ripple-button"
"warp-background"
"flickering-grid"
"animated-grid-pattern"
"retro-grid"
"ripple"
"dot-pattern"
"grid-pattern"
"interactive-grid-pattern"
"animated-theme-toggler"
"arc-timeline"
"highlighter"
"comic-text"
)

# Install each component
for component in "${components[@]}"; do
  echo "Installing $component..."
  npx shadcn@latest add "https://magicui.design/r/$component"
done

# After installing, move and overwrite components file in /components/magicui/* to /resources/js/components/ui/*
echo "Moving components to resources/js/components/ui..."
mkdir -p resources/js/components/ui
cp -r components/magicui/* resources/js/components/ui/

# Clean up the components directory
echo "Cleaning up components directory..."
rm -rf components/magicui