name: Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_APP_DIR: /laravel-app/
      SERVER_HTDOCS_DIR: /htdocs/
      FTP_PROTOCOL: ${{ secrets.FTP_PROTOCOL || 'ftps' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - name: Install PHP dependencies
        run: |
          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --no-progress \
            --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build assets
        run: |
          npm ci || npm install
          npm run build

      - name: Prepare deploy folders (split app and htdocs)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p deploy-app deploy-htdocs

          # Copy everything except public and dev-only stuff into deploy-app
          rsync -a --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            --exclude "tests/" \
            --exclude "public/" \
            --exclude ".env" \
            --exclude "storage/framework/cache/*" \
            --exclude "storage/framework/sessions/*" \
            --exclude "storage/logs/*" \
            ./ deploy-app/

          # Copy only the public folder contents into deploy-htdocs
          rsync -a public/ deploy-htdocs/

          # Adjust index.php to point to the sibling /laravel-app folder
          if [[ -f deploy-htdocs/index.php ]]; then
            sed -i "s|../vendor/autoload.php|../laravel-app/vendor/autoload.php|g" deploy-htdocs/index.php
            sed -i "s|../bootstrap/app.php|../laravel-app/bootstrap/app.php|g" deploy-htdocs/index.php
          fi

      - name: Compress vendor to speed up FTP upload
        run: |
          cd deploy-app
          zip -r vendor.zip vendor
          rm -rf vendor

      - name: Upload Laravel core (outside webroot)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ${{ env.FTP_PROTOCOL }}
          local-dir: deploy-app/
          server-dir: ${{ env.SERVER_APP_DIR }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**
            !vendor.zip

      - name: Upload public files (htdocs)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ${{ env.FTP_PROTOCOL }}
          local-dir: deploy-htdocs/
          server-dir: ${{ env.SERVER_HTDOCS_DIR }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
