name: Deploy Laravel to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HTDOCS_DIR: /htdocs/
      FTP_PROTOCOL: ${{ secrets.FTP_PROTOCOL || 'ftps' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer
          coverage: none

      - name: Install PHP dependencies
        run: |
          composer install \
            --no-dev \
            --prefer-dist \
            --no-interaction \
            --no-progress \
            --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Build assets
        run: |
          npm ci || npm install
          npm run build

      - name: Ensure public/build exists and copy build output
        shell: bash
        run: |
          set -euo pipefail
          # Create public directory if it doesn't exist
          mkdir -p public

          if [[ -d build ]]; then
            # Remove any previous public/build to ensure a clean copy
            rm -rf public/build || true
            # Copy build contents into public/build (preserve structure)
            rsync -a --delete build/ public/build/
          else
            echo "No top-level build/ directory found; skipping copy to public/build"
          fi

      - name: Prepare deploy package (all inside htdocs)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p deploy-htdocs

          # Copy everything except dev-only stuff
          rsync -a --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            --exclude "tests/" \
            --exclude ".env" \
            ./ deploy-htdocs/

          # Move public folder contents to root of htdocs
          rsync -a deploy-htdocs/public/ deploy-htdocs/
          rm -rf deploy-htdocs/public/

          # Fix index.php paths
          if [[ -f deploy-htdocs/index.php ]]; then
            sed -i "s|__DIR__.'/../vendor/autoload.php'|__DIR__.'/vendor/autoload.php'|g" deploy-htdocs/index.php
            sed -i "s|__DIR__.'/../bootstrap/app.php'|__DIR__.'/bootstrap/app.php'|g" deploy-htdocs/index.php
          fi

          # Force overwrite .htaccess
          cat > deploy-htdocs/.htaccess <<'EOF'
          <IfModule mod_rewrite.c>
              RewriteEngine On

              # Handle Authorization Header
              RewriteCond %{HTTP:Authorization} .
              RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

              # Redirect trailing slashes
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_URI} (.+)/$
              RewriteRule ^ %1 [L,R=301]

              # If request does not match a file or directory, route to index.php
              RewriteCond %{REQUEST_FILENAME} !-d
              RewriteCond %{REQUEST_FILENAME} !-f
              RewriteRule ^ index.php [L]

              # Deny access to sensitive files
              <FilesMatch "(artisan|.env|.git|.env.example|composer.json|composer.lock|package.json|webpack.mix.js|vite.config.js)">
                  Order allow,deny
                  Deny from all
              </FilesMatch>
          </IfModule>
          EOF

      - name: Write .env from secret
        shell: bash
        env:
          SECRET_ENV: ${{ secrets.ENV }}
        run: |
          set -euo pipefail
          # Ensure deploy directory exists (should from previous step)
          mkdir -p deploy-htdocs
          # Write the secret contents to the .env in the deploy directory safely
          printf '%s\n' "$SECRET_ENV" > deploy-htdocs/.env
          # Lock down perms just in case
          chmod 600 deploy-htdocs/.env || true

      - name: Upload to InfinityFree (htdocs)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ${{ env.FTP_PROTOCOL }}
          local-dir: deploy-htdocs/
          server-dir: ${{ env.SERVER_HTDOCS_DIR }}
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/node_modules/**
